---
# - name: Updates apt cache
#   apt: update_cache=yes

# - name: Upgrade existing apt packages
#   apt: upgrade=full

- name: Install apt packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - nginx
    - supervisor
    - build-essential
    - python-dev
    - python-setuptools
    - python-virtualenv
    - python-psycopg2
    - memcached
    - libmemcached-dev
    - postgresql-9.1
    - postgresql-server-dev-9.1
    - redis-server
