---
# - name: Install sentry
#   shell: "{{ app_env }}/bin/easy_install -UZ sentry creates={{ app_env }}/bin/sentry"

- name: Install sentry
  pip: name={{ item }} virtualenv={{ app_env }}
  with_items:
   - psycopg2
   - python-memcached
   - django-pylibmc
   - sentry
   - redis
   - hiredis
   - nydus

- name: Install sentry.conf.py
  template: src=sentry.conf.py dest={{ sentry_conf_file }} #owner={{ app_user }} group={{ app_group }}
  notify:
    - reload supervisor

- name: Migrate sentry db
  shell: "{{ app_env }}/bin/sentry --config={{ sentry_conf_file }} upgrade --noinput"

- name: Remove default nginx conf
  sudo_user: root
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Install sentry nginx conf
  sudo_user: root
  template: src=nginx-site.j2 dest=/etc/nginx/sites-enabled/sentry
  notify: restart nginx

- name: Install supervisor conf
  sudo_user: root
  template: src=supervisor.j2 dest=/etc/supervisor/conf.d/sentry.conf
  notify: reload supervisor
