---
- name: Setup group
  group: name={{ app_group }} state=present

- name: Setup user
  user: name={{ app_user }} state=present group={{ app_group }}

- name: Ensure directories exist
  file: state=directory path={{ item }} owner={{ app_user }} group={{ app_group }}
  with_items:
    - "{{ app_root }}"
    - "{{ app_conf }}"
    - "{{ app_log }}"
