---
app_user           : sentry
app_group          : sentry

app_root           : /srv/sentry
app_env            : "{{ app_root }}/env"
app_conf           : "{{ app_root }}/conf"
app_log            : "/var/log/nginx/sentry"

# Sentry config
sentry_conf_file   : "{{ app_conf }}/sentry.conf.py"
sentry_key         : secret
sentry_url_prefix  : http://something  # No trailing slash!
sentry_email       : sentry@something.com

# Email
smtp_server        : localhost
smtp_user          : ""
smtp_password      : ""
smtp_port          : 25
smtp_use_tls       : False

# Database
db_host            : localhost
db_name            : sentry
db_user            : sentry
db_password        : sentry
